### ISSUE TITLE
[CI] .xcconfig

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [jeong-hyeonHwang/CITest#1]
## ✨ 목표: .xcconfig로 숨겨야하는 Key를 관리해보자 (Actions Fail 멈춰...)
**1. Initial Project 추가**
<img width="637" alt="스크린샷 2023-04-04 오전 4 27 18" src="https://user-images.githubusercontent.com/96641477/229607701-af91c80f-40e4-4de3-8ad6-903a8fb98aa5.png">
- 아직까지는 잘 돌아감
- 당연함...private key나 파일 ref가 없으니까...

**2. .gitignore .xcconfig 추가 + Xcode .xcconfig 파일 추가 + Configuration 설정**
- 중간에 `Private.plist` 파일 추가한 이력(d8e832b)은 잠깐 무시... .plist 버전 다룰 때 언급 예정

|.pbxproj에 .xcconfig ref 추가 (7fae9f2)|.xcconfig 기본 Configuration 관련 설정 (14e0471)|
|:---:|:---:|
|<img width="481" alt="스크린샷 2023-04-04 오전 4 34 31" src="https://user-images.githubusercontent.com/96641477/229609117-2257da63-f98b-4477-a1ca-ee054c98079f.png">|<img width="438" alt="스크린샷 2023-04-04 오전 4 32 28" src="https://user-images.githubusercontent.com/96641477/229608762-aacad383-d857-4538-a980-18e7189ddcc7.png">|

|기본 설정은 Release였던 것 같은데 Configuration 설정을 Debug에만 해둬서 혹시나 해서 바꿔봄 (14e0471)|
|:---:|
|<img width="639" alt="스크린샷 2023-04-04 오전 4 34 10" src="https://user-images.githubusercontent.com/96641477/229609041-837af21e-37ad-4703-a57c-f4327c997454.png">|

**실제 사용 코드부**
```swift
// ViewController.swift line.19-23
        let str: String = {
            guard let str = Bundle.main.object(forInfoDictionaryKey: "TEST_KEY") as? String else { return "" }
            return str
        }()
        print(str)
```
|[Actions 결과: FAIL](https://github.com/jeong-hyeonHwang/CITest/actions/runs/4600150559)|
|:---:|
|<img width="953" alt="스크린샷 2023-04-04 오전 4 40 33" src="https://user-images.githubusercontent.com/96641477/229610428-56bee955-e678-4330-a2f4-77e5b2dd9d1f.png">|
- ㅎㅋ...Fail
- 당연함...파일 레퍼런스는 있는데 `.gitignore`처리해둬서 껍데기가 보이는 것? 처럼? 있지만? 사실 껍데기나 내용물이나 다 없음...

---

**Build Phase에 등록은 되어있지만, 실제 파일에 접근하는게 불가능함**
**-> 파일을 만들어버리면 된다...**

---

**3. Repository Private key 등록**
<img width="1130" alt="스크린샷 2023-04-04 오전 4 43 12" src="https://user-images.githubusercontent.com/96641477/229610928-be089ea5-77f0-4b37-bf2b-8ccd11a135a3.png">
- 키를 만들긴 했는데 어떻게 Actions에서 접근할 수 있게 만들지?

4. **.yml에서 `.xcconfig` 만들어주기**
**fcb6d9e**
```yml
// Build.yml Full Code
name: CI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup secrets.xcconfig
      run:  |
        echo '
        TEST_KEY = $secrets.TEST.KEY
        ' >> ./CITest/CITest/Secrets.xcconfig
    - name: Build Xcode
      run: |
        xcodebuild build -project ./CITest/CITest.xcodeproj -scheme CITest -destination "platform=iOS Simulator,name=iPhone 14,OS=latest"
```
**여기가 중요**
```yml
// Build.yml line.17-21
    - name: Setup secrets.xcconfig
      run:  |
        echo '
        TEST_KEY = $secrets.TEST.KEY
        ' >> ./CITest/CITest/Secrets.xcconfig
```
- .xcconfig 파일 내부 내용을 GitHub Actions Secret Key로 등록된 요소로 접근할 수 있게 도와주기
- 근데 빌드 단계에서는 코드 자체에 오류가 없는지만 보니까 사실 `echo '' >> ./CITest/CITest/Secrets.xcconfig` 이렇게만 처리해도 Success가 뜨지 않을까하는...

|[Actions 결과: Success](https://github.com/jeong-hyeonHwang/CITest/actions/runs/4600343359)|
|:---:|
|<img width="953" alt="스크린샷 2023-04-04 오전 4 53 00" src="https://user-images.githubusercontent.com/96641477/229612893-5f85fdf5-9dfe-463e-95d6-91e077fd21fc.png">|

---
### + alpha
- 이후로도 여러가지 테스트를 해봤는데
<img width="953" alt="스크린샷 2023-04-04 오전 4 55 52" src="https://user-images.githubusercontent.com/96641477/229613460-65610761-5222-4b7a-93f5-92cdc4edcfa0.png">

1. 새로운 xcconfig를 추가를 하거나
2. 이 xcconfig에 등록된 키를 Info.plist에 등록 후 코드에서 사용하거나

위의 경우에서는 여전히 Success

**하지만, Debug Configuration을 echo 해서 파일을 추가하는 작업이 없는 `Attempt.xcconfig`로 설정을 바꾸니까...?**
|[코드 링크](https://github.com/jeong-hyeonHwang/CITest/commit/238b9fb154bdc326fd3a922784c68fd4482d69d4)|
|:---:|
|<img width="639" alt="스크린샷 2023-04-04 오전 4 58 15" src="https://user-images.githubusercontent.com/96641477/229613968-f5404f88-b489-4131-8339-723a2e4f1f94.png">|

|[Actions 결과: FAIL](https://github.com/jeong-hyeonHwang/CITest/actions/runs/4600523709)|
|:---:|
|<img width="900" alt="스크린샷 2023-04-04 오전 5 01 05" src="https://user-images.githubusercontent.com/96641477/229614537-ed36eaec-c063-4a5c-a5a4-93f3d47613d2.png">|

## ✨ 결론
**Private Key가 있다면!**
- 해당 Repo -> Settings -> Security: Secrets and variables -> Actions에서 해당 키 추가
- 추가된 키를 .yml에서 echo를 통해 해당 파일을 만들어주기
